### ISSUE TITLE
About the project

### ISSUE THREAD

**Issue by fuatsengul** [FredrikSandell/ssh-hub#1]
Hello Fredrik,
I also have a project that involves Raspberry PIs at large.
I need to access them if any wrong happens but they will going up the air with 3G dongles. 
So reverse-ssh'ing the obvious solution.

After some time of research to find out a 'safe' way to keep my services away from unwanted parties, So, I found your project and I liked it. 
And I wanna get it going if you dropped at some point.
Can you confirm that is the copy of project is latest version?
It would better if you share finished version of your code. 

Thanks.

**Comment by FredrikSandell** [comment]
Hi Fuat,

Yes, it is the latest version. The concept works, I have a couple of pi's
running against an instace of ssh-hub. I have however not testet all client
shell scripts fully. I set up my pis partly manually.

Best of luck in your project!
Fredrik
Den 28 aug 2015 23:43 skrev "Fuat Şengül" notifications@github.com:

**Comment by FredrikSandell** [comment]
Updated the project a bit. It should now work out of the box. If it is still of use to you, please try it.

**Comment by fuatsengul** [comment]
thank you!
